apiVersion: v1
kind: Service
metadata:
  name: {{ include "mywebapp.fullname" . }}-service
  labels:
    {{- include "mywebapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP  # Use 'LoadBalancer' if you want to expose externally (requires cloud provider support)
  ports:
    - port: 80  # Exposed port on the Service
      targetPort: 8080  # Port on the container where the application is running
      protocol: TCP
      name: http
  selector:
    {{- include "mywebapp.selectorLabels" . | nindent 4 }}
