name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Determine Docker image tag
      id: get_version
      run: |
        if [ -n "${GITHUB_REF##refs/tags/*}" ]; then
          echo "No tag found, using commit hash"
          VERSION=$(echo "${GITHUB_SHA}" | cut -c1-7)
        else
          VERSION=${GITHUB_REF##refs/tags/}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 891377120087.dkr.ecr.us-west-2.amazonaws.com
        ECR_REPOSITORY: rakbank/demo
        VERSION: ${{ env.VERSION }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to EKS
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        VERSION: ${{ env.VERSION }}
      run: ./deploy.sh

